/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package org.boniardi.guesswords.helper;

import java.util.ArrayList;
import org.boniardi.guesswords.elements.AllElements;
import org.boniardi.guesswords.elements.Word;

/**
 *
 * @author mboniardi
 */
public class WordHelper {

    static ArrayList<String> getDuplicateTranslationList() {
        if (!AllElements.isInitailized()) {
            loadValues();
        }
        ArrayList<String> result = new ArrayList<>();
        for (Word word : AllElements.getInnerList()) {
            result.add(word.getFirstTranslation());
        }
        System.out.println("DuplicateListSize: "+result.size());
        return result;
    }

    static ArrayList<Word> getDuplicateWordList() {
        if (!AllElements.isInitailized()) {
            loadValues();
        }
        ArrayList<Word> result = new ArrayList<>();
        for (Word word : AllElements.getInnerList()) {
            result.add(new Word(word));
        }
        return result;
    }

    private static void loadValues() {
/**
        AllElements.addElement("ἡ ἀλκή, ῆς", "forza");
        AllElements.addElement("ἡ γνώμη, ης", "opinione");
        AllElements.addElement("ἡ εὐχή, ῆς", "preghiera");
        AllElements.addElement("ἡ σπουδή, ῆς", "solerzia");
        AllElements.addElement("ἡ λίμνη, ης", "lago");
        AllElements.addElement("ἡ τροφή, ῆς", "nutrimento");
        AllElements.addElement("ἡ μάχη, ης", "battaglia");
        AllElements.addElement("ἡ μέριμνα, ης", "affanno");
        AllElements.addElement("ἡ Μοῦσα, ης", "musa");
        AllElements.addElement("ἡ γλῶσσα, ης", "lingua");
        AllElements.addElement("ἡ ἧττα, ης", "sconfitta");
        AllElements.addElement("ἡ πονερία, ας", "malvagità");
        AllElements.addElement("ἡ προδοσία, ας", "tradimento");
        AllElements.addElement("ἡ πρεσβεία, ας", "ambasceria");
        AllElements.addElement("ἡ πολιτεία, ας", "costituzione");
        AllElements.addElement("ἡ αἰτία, ας", "causa");
        AllElements.addElement("ἡ ἀμέλεια, ας", "noncuranza");
        AllElements.addElement("ἡ ἐπιμέλεια, ας", "cura");
        AllElements.addElement("ἡ ἐλευθερία, ας", "libertà");
        AllElements.addElement("ἡ δουλεία, ας", "schiavitù");
        AllElements.addElement("ἡ βία, ας", "violenza");
        AllElements.addElement("ἡ εὐδαιμονία, ας", "felicità");
        AllElements.addElement("ἡ ἀτιμία, ας", "disonore");
        AllElements.addElement("ἡ ἐμπειρία, ας", "esperienza");
        AllElements.addElement("ἡ ἀπειρία, ας", "inersperienza");
        AllElements.addElement("ἡ ἑσπέρα, ας", "sera");
        AllElements.addElement("ἡ ἡμέρα, ας", "giorno");
        AllElements.addElement("ἡ σωτηρία, ας", "salvezza");
        AllElements.addElement("ἡ τιμωρία, ας", "vendetta");
        AllElements.addElement("ἡ κακία, ας", "malvagità");
        AllElements.addElement("ἡ ἀγγελία, ας", "notizia");
        AllElements.addElement("ἡ ἀδικία, ας", "ingiustizia");
        AllElements.addElement("ἡ δίκη, ης", "giustizia");
        AllElements.addElement("ἡ ἀλήθεια, ας", "verità");
        AllElements.addElement("ἡ ἀτυχία, ας", "disgrazia");
        AllElements.addElement("ἡ τύχη, ης", "fortuna, sorte");
        AllElements.addElement("ἡ μοῖρα, ας", "destino");
        AllElements.addElement("ἡ ἅμαξα, ας", "carro (guerra)");
        AllElements.addElement("ἡ θάλασσα, ης", "mare");
        AllElements.addElement("ἡ δημοκρατία, ας", "democrazia");
        AllElements.addElement("ἡ ολιγαρχία, ας", "oligarchia");
        AllElements.addElement("ἡ μέλισσα, ης", "ape");
        AllElements.addElement("ἡ ἀμαθία, ας", "ignoranza");
        AllElements.addElement("ἡ αἰσχυνη, ης", "vergogna");
        AllElements.addElement("ἡ διαβολή, ης", "calunnia");
        AllElements.addElement("ἡ δόξα, ης", "opinione, apparenza");
        AllElements.addElement("ἡ ἀρχή, ῆς", "comando/inizio");
        AllElements.addElement("ἡ βουλή, ῆς", "consiglio");
        AllElements.addElement("ἡ τόλμα, ης", "sfrontatezza");

        AllElements.addElement("ἡ ἀδελφή, ῆς", "sorella");
        AllElements.addElement("ἡ τιμή, ῆς", "onore");
        AllElements.addElement("ἡ ψυχή, ῆς", "anima");
        AllElements.addElement("ἡ λύπη, ης", "dolore");
        AllElements.addElement("ἡ ταφή, ῆς", "sepoltura");
        AllElements.addElement("ἡ φυγή, ῆς", "fuga");
        AllElements.addElement("ἡ ὀργή, ῆς", "ira");
        AllElements.addElement("ἡ ἀγορά, ᾶς", "piazza");
        AllElements.addElement("ἡ ἀνδρεία, ας", "valore");
        AllElements.addElement("ἡ ἀνανδρία, ας", "viltà");
        AllElements.addElement("ἡ ἐκκλησία, ας", "riunione");
        AllElements.addElement("ἡ ἀθανασία, ας", "immortalità");
        AllElements.addElement("ἡ ἀθυμία, ας", "scoramento");
        AllElements.addElement("ἡ ἀπιστία, ας", "sfiducia, incredulità");
        AllElements.addElement("ἡ βασίλεια, ας", "regina");
        AllElements.addElement("ἡ βασιλεία, ας", "regno");
        AllElements.addElement("ἡ γεωργία, ας", "agricoltura");
        AllElements.addElement("ἡ ἡγεμονία, ας", "egemonia");
        AllElements.addElement("ἡ θυσία, ας", "sacrificio");
        AllElements.addElement("ἡ παιδεία, ας", "educazione");
        AllElements.addElement("ἡ σοφία, ας", "saggezza");
        AllElements.addElement("ἡ φιλία, ας", "amicizia, amore");
        AllElements.addElement("ἡ πολιορκία, ας", "assedio");
        AllElements.addElement("ἡ λύρα, ας", "lira");
        AllElements.addElement("ἡ ναυμαχία, ας", "battaglia in mare");
        AllElements.addElement("ἡ μάχαιρα, ας", "spada");
        AllElements.addElement("ἡ συμμαχία, ας", "alleanza");
        AllElements.addElement("ἡ πενία, ας", "povertà");
        AllElements.addElement("ἡ πεῖνα, ης", "fame");
        AllElements.addElement("ἡ δίψα, ης", "sete");
        AllElements.addElement("ἡ σελήνη, ης", "luna");
        AllElements.addElement("ἡ πληγή, ῆς", "colpo");
        AllElements.addElement("ἡ ἡδονή, ῆς", "piacere");
        AllElements.addElement("ἡ θεράπαινα, ης", "schiava");
        AllElements.addElement("ἡ δέσποινα, ης", "padrona");
        AllElements.addElement("ἡ νίκη, ης", "vittoria");
        AllElements.addElement("ἡ μνήμη, ης", "memoria");
        AllElements.addElement("ἡ μορφή, ῆς", "forma");
        AllElements.addElement("ἡ σιγή, ῆς", "silenzio");
        AllElements.addElement("ἡ ἀνάγκη, ης", "necessità");
        AllElements.addElement("ἡ ἀρετή, ῆς", "virtù");
        AllElements.addElement("ἡ βλάβη, ης", "danno");
        AllElements.addElement("ἡ δάφνη, ης", "lauro, alloro");
        AllElements.addElement("ἡ γραφή, ῆς", "pittura, scrittura");
        AllElements.addElement("ἡ εἰρήνη, ης", "pace");
        AllElements.addElement("ἡ φήμη, ης", "fama");
        AllElements.addElement("ἡ φωνή, ῆς", "voce");
        AllElements.addElement("ἡ τέχνη, ης", "arte");
        AllElements.addElement("ἡ σχολή, ῆς", "ozio");
        AllElements.addElement("ἡ παρασκευή, ῆς", "allestrimento");

        AllElements.addElement("ἡ ᾠδή, ῆς", "ode, canto");
        AllElements.addElement("ἡ ἰδέα, ας", "aspetto, idea");
        AllElements.addElement("ἡ καρδία, ας", "cuore");
        AllElements.addElement("ἡ κεφαλή, ῆς", "testa");
        AllElements.addElement("ἡ θέα, ας", "vista");
        AllElements.addElement("ἡ θεά, ᾶς", "dea");
        AllElements.addElement("ἡ κόρα, ας", "fanciulla");
        AllElements.addElement("ἡ στρατεία, ας", "spedizione militare");
        AllElements.addElement("ἡ στρατιά, ᾶς", "esercito");
        AllElements.addElement("ἡ ἔχθρα, ας", "inimicizia");
        AllElements.addElement("ὁ ἀθλητής, οῦ", "atleta");
        AllElements.addElement("ὁ δεσπότης, ου", "padrone");
        AllElements.addElement("ὁ δικαστής, οῦ", "giudice");
        AllElements.addElement("ὁ θεατής, οῦ", "spettatore");
        AllElements.addElement("ὁ κλέπτης, ου", "ladro");
        AllElements.addElement("ὁ μαθητής, οῦ", "scolaro");
        AllElements.addElement("ὁ ναύτης, ου", "marinaio");
        AllElements.addElement("ὁ νεανίας, ου", "giovane");
        AllElements.addElement("ὁ νομοθέτης, ου", "legislatore");
        AllElements.addElement("ὁ οἰκέτης, ου", "servo");
        AllElements.addElement("ὁ ποιητής, οῦ", "poeta");
        AllElements.addElement("ἡ ἐπιστήμη, ης", "scienza");
        AllElements.addElement("ἡ κραυγή, ῆς", "grido");
        AllElements.addElement("ἡ ἐπιστολή, ῆς", "lettera");
        AllElements.addElement("ὁ προδότης, ου", "traditore");
        AllElements.addElement("ὁ στρατιώτης, ου", "soldato");
        AllElements.addElement("ὁ ὁπλίτης, ου", "soldato");
        AllElements.addElement("ὁ τραυματίας, ου", "ferito");
        AllElements.addElement("ὁ τοξότης, ου", "arciere");
        AllElements.addElement("ὁ πολίτης, ου", "cittadino");
        AllElements.addElement("ὁ τεχνίτης, ουv", "artigiano");
        AllElements.addElement("ὁ πρεσβύτης, ου", "anziano");
        AllElements.addElement("ὁ ταμίας, ου", "tesoriere");
        AllElements.addElement("ὁ σοφιστής, ου", "sofista");
        AllElements.addElement("ὁ κυβερνήτης, ου", "timoniere");
 **/       
        
/**        
AllElements.addElement("ἄγ","condurre", "guidare", "trascorrere");
AllElements.addElement("ἄγω","io conduco", "io guido");
AllElements.addElement("ἀγ-ών -ῶνος, ὁ","agone", "gara", "lotta");
AllElements.addElement("ἀν-άγ-ω","io salpo", "io parto");
AllElements.addElement("ἄξ-ιος, -α, -ον","degno", "valido");
AllElements.addElement("ἀξ-ιόω", "io stimo", "degno", "io decido");
AllElements.addElement("ἀξ-ίωμα, -ατος, τό", "dignità", "stima", "onore", "reputazione", "valore");
AllElements.addElement("ἀξ-ία, -ας, ἡ","pregio", "valore", "prezzo");
AllElements.addElement("ἀν-άξ-ιος, -ον","indegno", "immeritevole", "immeritato");
AllElements.addElement("δι-άγω","io trascorro", "io vivo", "io passo il tempo");
AllElements.addElement("στρατ-ηγ-ός, -οῦ, ὁ","stratego", "comandante", "generale");
AllElements.addElement("ἀγγελ","annunciare", "riferire");
AllElements.addElement("ἀγγέλλ-ω", "io riferisco", "io annuncio");
AllElements.addElement("ἀγγελ-ία, -ας, ἡ", "messaggio", "notizia", "annuncio");
AllElements.addElement("ἄγγελ-ος, -ου, ὁ", "messaggero", "nunzio");
AllElements.addElement("ἀπ-αγγέλλ-ω", "io riferisco", "io annuncio");
AllElements.addElement("εἰσ-αγγελ-ία, -ας, ἡ", "processo", "denuncia");
AllElements.addElement("εὐ-αγγέλ-ιον, -ου, τό", "buona novella");
AllElements.addElement("ἀγερ/ἀγορ/ἀγυρ", "radunare");
AllElements.addElement("ἀγείρ-ω", "io raduno", "io raccolgo", "io aduno");
AllElements.addElement("ἀγορ-ά, -ᾶς, ἡ", "piazza", "assemblea");
AllElements.addElement("ἀγορά-ομαι", "io mi raduno", "io parlo in pubblico");
AllElements.addElement("ἀγορ-εύω", "io parlo in pubblico");
AllElements.addElement("κατ-ηγορ-έω", "io accuso", "io parlo contro");
AllElements.addElement("κατ-ήγορ-ος, -ου, ὁ", "accusatore");
AllElements.addElement("πανήγυρις, -εως, ἡ", "assemblea");
AllElements.addElement("ἀγρ", "campo, campagna", "terreno");
AllElements.addElement("ἀγρ-ός, -οῦ, ὁ", "campo", "campagna", "terreno");
AllElements.addElement("ἄγρ-ιος, -α, -ον", "agreste", "selvatico", "selvaggio");
AllElements.addElement("ἄγρ-οικος, -ον", "agreste", "rustico", "campagnolo", "rozzo");
AllElements.addElement("ἄγρ-οικία, -ας, ἡ", "rozzezza", "rusticità");
AllElements.addElement("ἀειδ/ἀοιδ/ᾀδ/ᾠδ", "canto", "cantare");
AllElements.addElement("ἀείδ-ω", "io canto");
AllElements.addElement("ᾄδ-ω", "io canto");
AllElements.addElement("ἀοιδ-ός, -οῦ, ὁ", "aedo", "cantore");
AllElements.addElement("ἀοιδ-ή, -ῆς, ἡ", "canto", "canzone", "poesia");
AllElements.addElement("ᾠδ-ή, -ῆς, ἡ", "canto", "poesia");
AllElements.addElement("ᾠδ-εῖον, -ου, τό", "odeon");
AllElements.addElement("αἰδ/αἰδε", "rispetto", "pudore");
AllElements.addElement("αἰδέομαι", "io rispetto", "io mi vergogno", "io provo vergogna", "io temo");
AllElements.addElement("αἰδ-ώς, -οῦς, ἡ", "rispetto", "pudore", "vergogna");
AllElements.addElement("αἰδ-οῖος, -α, -ον", "rispettoso", "degno di rispetto", "vergognoso", "rispettato");
AllElements.addElement("αἰν/αἰνε", "lodare", "lode", "elogio", "elogiare");
AllElements.addElement("αἰνέ-ω", "io lodo", "io elogio");
AllElements.addElement("ἔπ-αιν-ος, -ου, ὁ", "lode", "elogio");
AllElements.addElement("παρ-αινέ-ω", "io esorto", "io ammonisco");
AllElements.addElement("αἱρε", "prendere", "scegliere");
AllElements.addElement("αἱρέ-ω", "io prendo", "io scelgo");
AllElements.addElement("αἵρε-σις, -εως, ἡ", "scelta", "dottrina");
AllElements.addElement("ἀν-αιρέ-ω", "io elimino", "io uccido");
AllElements.addElement("δι-αίρε-σις, -εως, ἡ", "separazione");
AllElements.addElement("αἰσθ/αἰσθη", "sensazione", "percezione", "sentire", "accorgersi");
AllElements.addElement("αἰσθ-άν-ομαι", "io mi accorgo", "io percepisco", "io sento");
AllElements.addElement("αἴσθη-σις, -εως, ἡ", "sensazione", "percezione");
AllElements.addElement("αἰσθη-τός, -ή, -όν", "sensibile", "percepibile");
AllElements.addElement("αἰσθη-τικός, -ή, -όν", "sensibile", "sensoriale");
AllElements.addElement("αἰσχ", "brutto", "turpe");
AllElements.addElement("αἰσχ-ύνω", "io disonoro");
AllElements.addElement("αἰσχ-ύνομαι", "io mi vergogno");
AllElements.addElement("αἰσχ-ρός, -ά, -όν", "brutto", "turpe");
AllElements.addElement("αἰσχ-ύνη, -ης, ἡ", "vergogna");
AllElements.addElement("αἰτ/αἰτε", "chiedere", "domandare", "domanda", "richiesta");
AllElements.addElement("αἰτέ-ω", "io chiedo", "io domando", "io richiedo");
AllElements.addElement("αἴτη-σις, -εως, ἡ", "richiesta", "domanda");
AllElements.addElement("αἰτ-ία, -ας, ἡ", "causa", "colpa", "responsabilità");
AllElements.addElement("αἴτ-ιος, -α, -ον", "responsabile", "colpevole");
AllElements.addElement("ἀκου/ἀκοϜ/ἀκο", "ascoltare", "ascolto", "udito", "udire", "sentire");
AllElements.addElement("ἀκού-ω", "io ascolto", "io odo", "io sento");
AllElements.addElement("ἄκου-σμα, -τος, τό", "racconto", "ascolto");
AllElements.addElement("ὑπ-ήκοος, ὁ", "suddito", "sottomesso");
**/
/**
AllElements.addElement("ἐδ/ὀδ/ὠδ", "cibo", "alimento", "mangiare", "cibarsi");
AllElements.addElement("ἐσ-θίω", "mangio");
AllElements.addElement("ἐδ-ωδ-ή, -ῆς, ἡ", "cibo", "alimento");
AllElements.addElement("ὀδ-ούς, -όντος, ὁ", "dente");
AllElements.addElement("ἐθ/ἠθ/ὠθ", "abitudine");
AllElements.addElement("ἔθ-ος, ους, τό", "abitudine", "tradizione");
AllElements.addElement("ἦθ-ος, -ους, τό", "abitudine", "carattere", "personalità", "indole");
AllElements.addElement("εὐ-ήθης, -ες", "buono", "semplice", "onesto", "dabbene", "ingenuo");
AllElements.addElement("εὐ-ήθει-α, -ας, ἡ", "bontà", "semplicità", "dabbenaggine", "ingenuità");
AllElements.addElement("ἐθ-ίζω", "io abituo");
AllElements.addElement("εἰ/ἰ", "andare");
AllElements.addElement("εἶ-μι", "io vado", "io andrò");
AllElements.addElement("ἄπ-ει-μι", "io me ne vado", "io parto", "io vado via");
AllElements.addElement("ἔξ-ει-μι", "io esco", "io vado fuori");
AllElements.addElement("ἐλευθερ", "libero", "libertà");
AllElements.addElement("ἐλεύθερ-ος, -α, -ον", "libero", "indipendente", "liberale");
AllElements.addElement("ἐλευθερ-ία, -ας, ἡ", "libertà", "liberalità", "indipendenza");
AllElements.addElement("ἐλευθερ-όω", "io libero", "io rendo libero");
AllElements.addElement("ἐλπιδ/ἐλπ/ὀλπ", "sperare", "speranza", "aspettativa", "prevedere");
AllElements.addElement("ἐλπίζ-ω", "io spero", "io prevedo");
AllElements.addElement("ἐλπίς, -ίδος, ἡ", "speranza", "previsione");
AllElements.addElement("ἄ-ελπ-τος, -ον", "insperato", "imprevisto", "inatteso");
AllElements.addElement("ἐπ/ὀπ", "parola", "dire");
AllElements.addElement("ἔπ-ος, -ους, τό", "parola", "verso");
AllElements.addElement("εἶπ-ον", "io dissi");
AllElements.addElement("ἐρ/ῥη", "parola", "parlare", "dire");
AllElements.addElement("εἴρ-ω", "io dico", "io parlo");
AllElements.addElement("ῥῆ-σις, -εως, ἡ", "discorso", "intervento");
AllElements.addElement("παρ-ρη-σία, -ας, ἡ", "libertà di parola", "confidenza", "franchezza", "licenza");
AllElements.addElement("ῥή-τωρ, -τορος, ὁ", "oratore", "retore", "politico", "uomo politico");
AllElements.addElement("ῥητορική (τέχνη), ἡ", "retorica");
AllElements.addElement("ἐργ/ὀργ/ῥεγ", "lavorare", "lavoro", "azione", "opera");
AllElements.addElement("ἔργ-ον, -ου, τό", "azione", "opera", "lavoro", "impresa");
AllElements.addElement("ἐργ-άζομαι", "io lavoro", "io faccio");
AllElements.addElement("εὐ-εργ-έτης, -ου, ὁ", "benefattore");
AllElements.addElement("γε-ωργ-ός, -οῦ, ὁ", "agricoltore", "contadino");
AllElements.addElement("ἐν-έργ-εια, -ας, ἡ", "efficacia", "attività");
AllElements.addElement("ὄργ-ανον, -ου, τό", "strumento");
AllElements.addElement("ῥέζ-ω", "io sacrifico", "io celebro un rito", "io offro un sacrificio");
AllElements.addElement("ἐριδ", "lite", "litigare", "litigio", "rivalità", "gara");
AllElements.addElement("ἔρις, -ιδος, ἡ", "lite", "litigio", "discordia", "contesa");
AllElements.addElement("ἐρίζ-ω", "io litigo", "io contendo", "io gareggio");
AllElements.addElement("εὑρ-ε/εὑρ-η", "trovare", "inventare", "escogitare", "invenzione");
AllElements.addElement("εὑρ-ίσκω", "io trovo", "io invento", "io escogito");
AllElements.addElement("εὕρε-σις, -εως, ἡ", "scoperta", "invenzione", "trovata");
AllElements.addElement("εὕρη-μα, -τος, τό", "scoperta", "invenzione", "trovata");
AllElements.addElement("εὑρε-τής, -οῦ, ὁ", "inventore", "scopritore");
AllElements.addElement("ἐχ/ἑχ/σχ-ε/σχ-η/ὀχ", "avere", "tenere", "stare");
AllElements.addElement("ἔχ-ω", "io ho", "io possiedo", "io tengo");
AllElements.addElement("σχέ-σις, -εως, ἡ", "condizione", "disposizione", "situazione");
AllElements.addElement("σχῆ-μα, -τος, τό", "aspetto", "figura", "portamento");
AllElements.addElement("ἠνί-οχος, -ου, ὁ", "auriga", "cocchiere");
AllElements.addElement("δε/δη", "legare");
AllElements.addElement("δέ-ω", "io lego");
AllElements.addElement("δε-σμός, -οῦ, ὁ", "legame", "catena", "ceppo", "vincolo");
AllElements.addElement("δε-σμώτης, -ου, ὁ", "prigioniero");
AllElements.addElement("δε-σμώτηριον, -ου, τό", "prigione", "carcere");
AllElements.addElement("δέ-σις, -εως, ἡ", "legame", "vincolo");
AllElements.addElement("δε-ι/δοι/δι", "temere", "timore", "paura");
AllElements.addElement("δείδ-ω", "io temo", "io ho paura");
AllElements.addElement("δέ-ος, -ους, τό", "timore", "paura");
AllElements.addElement("δει-λός, -ή, -όν", "vile", "vigliacco");
AllElements.addElement("δει-νός, -ή, -όν", "terribile", "straordinario", "eccezionale");
AllElements.addElement("δεικ", "mostrare", "indicare");
AllElements.addElement("δείκ-νυμι", "io mostro", "io indico", "io dimostro");
AllElements.addElement("ἔv-δειξ-ις, -εως, ἡ", "denuncia", "delazione");
AllElements.addElement("ἐπί-δειξ-ις, -εως, ἡ", "dimostrazione", "indicazione");
AllElements.addElement("παρά-δειγ-μα, -τος, τό", "modello", "esempio");
AllElements.addElement("δεχ/δεκ/δοχ/δοκ", "accettare", "accogliere", "ricevere");
AllElements.addElement("δέχ-ομαι", "io accetto", "io ricevo");
AllElements.addElement("δια-δέχ-ομαι", "io eredito", "io succedo");
AllElements.addElement("δια-δοχ-ή, -ῆς, ἡ", "eredità", "successione");
AllElements.addElement("δωρο-δοκ-έω", "io mi lascio corrompere", "io corrompo");
AllElements.addElement("δευ/(δεϜ)/δε-η", "mancanza", "mancare", "bisogno");
AllElements.addElement("δέ-ω, δέ-ομαι", "io chiedo", "io ho bisogno");
AllElements.addElement("δεῖ", "bisogna");
AllElements.addElement("ἐν-δε-ής, -ές", "bisognoso", "manchevole");
AllElements.addElement("δέ-ον, -τό", "necessità", "necessario", "dovere");
AllElements.addElement("δηλ", "chiaro", "evidente", "ovvio", "palese");
AllElements.addElement("δῆλ-ος, -η, -ον", "chiaro", "ovvio", "palese", "evidente");
AllElements.addElement("δηλ-όω", "io chiarisco", "io manifesto", "io mostro", "io rivelo");
AllElements.addElement("ἄ-δηλ-ος, -ον", "incerto", "sconosciuto", "oscuro", "ignoto");
AllElements.addElement("δημ", "popolo", "demo");
AllElements.addElement("δῆμ-ος, -ου, ὁ", "popolo", "paese");
AllElements.addElement("δημ-όσιος, -α, -ον", "pubblico", "popolare", "comune", "statale");
AllElements.addElement("δημ-αγωγός, -οῦ, ὁ", "demagogo", "capopopolo");
AllElements.addElement("δημ-εύω", "io confisco", "io rendo pubblico");
AllElements.addElement("διδακ/διδαχ", "insegnare", "insegnamento");
AllElements.addElement("διδάσκ-ω", "io insegno");
AllElements.addElement("διδάσκ-αλος, -ου, ὁ", "maestro", "insegnante");
AllElements.addElement("διδασκαλ-εῖον, -ου, τό", "scuola");
AllElements.addElement("διδαχ-ή, -ῆς, ἡ", "insegnamento");
AllElements.addElement("δίδαξις, -εως, ἡ", "insegnamento");
AllElements.addElement("δικ", "giustizia");
AllElements.addElement("δίκ-η, -ης, ἡ", "giustizia", "processo");
AllElements.addElement("δικ-άζω", "io amministro la giustizia", "io giudico");
AllElements.addElement("δικ-αστής, -οῦ, ὁ", "giudice");
AllElements.addElement("δικ-αστήριον, -ου, τό", "tribunale");
AllElements.addElement("δίκ-αιος, -α, -ον", "giusto");
AllElements.addElement("δικ-αιοσύνη, -ης, ἡ", "giustizia");
AllElements.addElement("ἄ-δικ-ος, -ον", "ingiusto");
AllElements.addElement("ἀ-δίκ-ημα, -τος, τό", "ingiustizia", "azione ingiusta", "reato");
AllElements.addElement("ἀ-δικ-ία, -ας, ἡ", "ingiustizia");
AllElements.addElement("δοκ-η", "sembrare", "credere", "opinione", "fama");
AllElements.addElement("δοκέ-ω", "io sembro", "io ritengo");
AllElements.addElement("δοκεῖ", "sembra");
AllElements.addElement("δόξ-α, -ης, ἡ", "opinione", "fama");
AllElements.addElement("δοξ-άζω", "io ritengo", "io credo");
AllElements.addElement("δόγ-μα, -τος, τό", "opinione", "credenza", "reputazione");
AllElements.addElement("δόκ-ησις, -εως, ἡ", "opinione", "credenza", "reputazione");
AllElements.addElement("προσ-δοκ-άω", "io prevedo", "io mi aspetto");
AllElements.addElement("ἀ-προσ-δόκ-ητος, -ον", "inatteso", "imprevisto");
AllElements.addElement("ἄ-δοξ-ος, -ον", "inglorioso", "sconosciuto", "senza gloria");
AllElements.addElement("ἔν-δοξ-ος, -ον", "famoso", "celebre", "rinomato");
AllElements.addElement("παρά-δοξ-ος, -ον", "inatteso", "imprevisto", "inaspettato", "imprevedibile");
AllElements.addElement("δουλ", "schiavo", "servo", "schiavitù", "servitù");
AllElements.addElement("δοῦλ-ος, -ου, ὁ", "schiavo", "servo");
AllElements.addElement("δουλ-εύω", "io sono schiavo", "io servo", "io sono servo");
AllElements.addElement("δουλ-εία, -ας, ἡ", "servitù", "schiavitù");
AllElements.addElement("δυνα", "potere", "potenza");
AllElements.addElement("δύνα-μαι", "io posso", "io sono capace", "io sono in grado");
AllElements.addElement("δύνα-μις, -εως, ἡ", "potenza", "capacità", "forza", "forza militare", "esercito");
AllElements.addElement("δυνα-τός, -ή, όν", "possibile", "capace", "potente");
AllElements.addElement("ἄ-δύνα-τος, όν", "impossibile", "incapace", "invalido");
AllElements.addElement("δυνά-στης, -ου, ὁ", "capo", "re", "dinasta");
AllElements.addElement("δυνα-στεύω", "io domino", "io ho il potere", "io governo", "io esercito il potere");
AllElements.addElement("δυνα-στεία, -ας, ἡ", "potenza", "potere");
AllElements.addElement("δω/δο", "dare", "donare", "dono");
AllElements.addElement("δί-δω-μι", "io do", "io dono", "io offro");
AllElements.addElement("δῶ-ρον, -ου, τό", "dono", "regalo", "offerta");
AllElements.addElement("δω-ρεά, -ᾶς, ἡ", "dono", "regalo", "offerta");
AllElements.addElement("δωρο-δοκ-έω", "io accetto doni", "io mi faccio corrompere", "io corrompo");
AllElements.addElement("δωρο-δοκ-ία, -ας, ἡ", "corruttibilità", "venalità", "corruzione");
AllElements.addElement("δό-σις, -εως, ἡ", "contributo", "donazione");
AllElements.addElement("δό-τήρ, -ος, ὁ", "dispensatore", "donatore");
AllElements.addElement("προ-δί-δω-μι", "io tradisco");
AllElements.addElement("προ-δό-της, -ου, ὁ", "traditore");
AllElements.addElement("προ-δο-σία, -ας, ἡ", "tradimento");
AllElements.addElement("γαμ-ε", "sposare", "sposarsi", "nozze", "matrimonio");
AllElements.addElement("γαμέ-ω", "io sposo");
AllElements.addElement("γάμ-ος, -ου, ὁ", "matrimonio", "nozze", "sposalizio");
AllElements.addElement("γαμέ-της, -ου, ὁ", "marito", "sposo");
AllElements.addElement("γεν-ε/γον/γν", "nascere", "generare", "generazione", "nascita", "genere", "stirpe");
AllElements.addElement("γί-γν-ομαι", "io nasco", "io divento", "io sono");
AllElements.addElement("γεν-νάω", "io genero", "io produco");
AllElements.addElement("γέν-ος, -ους, τό", "genere", "stirpe", "razza", "famiglia", "specie");
AllElements.addElement("γένε-σις, -εως, ἡ", "generazione", "origine", "nascita");
AllElements.addElement("γενεά, -ᾶς, ἡ", "generazione", "stirpe", "razza", "specie");
AllElements.addElement("γον-εύς, -έως, ὁ", "genitore");
AllElements.addElement("γν-ήσιος, -α, ον", "legittimo", "autentico");
AllElements.addElement("γεν-ναῖος, -α, ον", "nobile");
AllElements.addElement("πρό-γον-ος, -ον", "antenato", "avo", "progenitore");
AllElements.addElement("εὐ-γεν-ής, -ές", "nobile");
AllElements.addElement("γηρ", "vecchio", "vecchiaia");
AllElements.addElement("γῆρ-ας, -ως, τό", "vecchiaia", "vecchiezza");
AllElements.addElement("γηρ-άσκω", "io invecchio", "io divento vecchio", "io sono vecchio");
AllElements.addElement("γηρ-αιός, -ά, -όν", "vecchio", "anziano");
AllElements.addElement("γνο/γνω", "conoscere", "conoscenza");
AllElements.addElement("γι-γνώ-σκω", "io conosco", "io so");
AllElements.addElement("γνῶ-σις, -εως, ἡ", "conoscenza");
AllElements.addElement("πρό-γνω-σις, -εως, ἡ", "previsione", "prognosi");
AllElements.addElement("γνω-τός, -ή, -όν", "conosciuto", "noto", "famoso", "celebre");
AllElements.addElement("γνώ-μη, -ης, ἡ", "conoscenza", "opinione", "intelligenza");
AllElements.addElement("συγ-γνώ-μη, -ης, ἡ", "comprensione", "perdòno");
AllElements.addElement("ἀνα-γι-γνώ-σκω", "leggo", "riconosco");
AllElements.addElement("ἀ-γνο-έω", "io ignoro", "io non so");
AllElements.addElement("ἄ-γνο-ια, -ας, ἡ", "ignoranza");
AllElements.addElement("ἄ-γνο-τος, -ον", "ignorato", "sconosciuto", "ignoto");
AllElements.addElement("γραφ", "scrivere", "scrittura", "disegnare", "disegno");
AllElements.addElement("γράφ-ω", "io scrivo", "io disegno");
AllElements.addElement("γραφ-ή, -ῆς, ἡ", "scrittura", "scritto", "disegno");
AllElements.addElement("γραφ-εύς, -έως, ὁ", "scrittore", "disegnatore");
AllElements.addElement("γράμ-μα, -τος, τό", "scrittura", "disegno", "lettera");
AllElements.addElement("γραμ-ματεύς, -έως, ὁ", "scrivano", "segretario");
AllElements.addElement("ἄγραφος, -ον", "non scritto");
AllElements.addElement("γυμν", "nudo", "denudare");
AllElements.addElement("γυμν-ός, -ή, -όν", "nudo", "spoglio", "svestito");
AllElements.addElement("γυμνό-ω", "io spoglio", "io denudo", "io scopro", "io svesto");
AllElements.addElement("γυμν-άσιον, -ου, τό", "ginnasio", "palestra");
AllElements.addElement("γυναικ", "donna");
AllElements.addElement("γυνή, γυναικ-ός, ἡ", "donna", "moglie");
AllElements.addElement("γυναικ-εῖος, -α, -ον", "femminile", "muliebre", "di donna", "da donna");
AllElements.addElement("βα/βη/βαν", "andare");
AllElements.addElement("βαίν-ω", "io vado");
AllElements.addElement("βῆ-μα, -τος, τό", "podio", "tribuna", "pedana");
AllElements.addElement("ἀνα-βαίν-ω", "io salgo");
AllElements.addElement("ἀνά-βασις, -εως, ἡ", "salita", "andata");
AllElements.addElement("διά-βαίν-ω", "io attraverso");
AllElements.addElement("διά-βασις, -εως, ἡ", "attraversamento", "traversata");
AllElements.addElement("κατα-βαίν-ω", "io scendo", "io ritorno");
AllElements.addElement("κατά-βασις, -εως, ἡ", "discesa", "ritorno");
AllElements.addElement("συμ-βαίν-ω", "io càpito");
AllElements.addElement("ἄ-βα-τος, -ον", "inaccessibile");
AllElements.addElement("βαλ/βολ/βελ/βλη", "lanciare", "gettare", "colpire");
AllElements.addElement("βάλλ-ω", "io colpisco", "io lancio");
AllElements.addElement("βλ-ῆμα, -τος, τό", "colpo", "lancio", "ferita");
AllElements.addElement("βολ-ή, -ῆς, ἡ", "lancio", "dardo", "colpo");
AllElements.addElement("βέλ-ος, -ους, τό", "dardo", "giavellotto", "lancia", "freccia");
AllElements.addElement("μετα-βολ-ή, -ῆς, ἡ", "cambiamento", "trasformazione", "cambio", "mutamento");
AllElements.addElement("ὑπερ-βολ-ή, -ῆς, ἡ", "eccesso", "esagerazione", "superiorità", "superamento");
AllElements.addElement("σύμ-βολ-ον, -ου, τό", "accordo", "contratto");
AllElements.addElement("βαρ", "peso", "pesante");
AllElements.addElement("βαρ-ύς, -εῖα, -ύ", "pesante", "grave");
AllElements.addElement("βάρ-ος, -ους, τό", "peso", "pesantezza");
AllElements.addElement("βαρ-ύνω", "io appesantisco");
AllElements.addElement("βασιλ", "re", "regnare", "regno");
AllElements.addElement("βασιλ-εύς, -έως, ὁ", "re", "sovrano");
AllElements.addElement("βασιλ-εύω", "io regno", "io sono re");
AllElements.addElement("βασίλ-ειος, -α, -ον", "regale", "regio", "reale");
AllElements.addElement("βασίλ-εια, -ας, ἡ", "regina");
AllElements.addElement("ἁλ/ἁλω", "presa", "cattura", "essere preso", "essere catturato", "essere conquistato");
AllElements.addElement("ἁλ-ίσκομαι", "io sono catturato", "io sono preso", "io sono conquistato");
AllElements.addElement("ἅλ-ωσις, -εως, ἡ", "cattura", "presa", "conquista");
AllElements.addElement("ἀν-αλ-ίσκω", "io consumo", "io distruggo", "io spendo", "io perdo");
AllElements.addElement("ἀλγ", "dolore", "sofferenza", "afflizione");
AllElements.addElement("ἀλγ-έω", "io soffro", "io sento dolore", "io provo dolore");
AllElements.addElement("ἀλγ-ος, -ους, τό", "dolore", "sofferenza", "afflizione");
AllElements.addElement("ἀλγ-ειν-ός, -ή, -όν", "doloroso", "penoso");
AllElements.addElement("ἀλγ-ηδών, -όνος, ἡ", "dolore", "pena", "sofferenza");
AllElements.addElement("ἀλλα/ἀλλαγ/ἀλλαχ", "scambio", "scambiare", "cambio", "cambiare");
AllElements.addElement("ἀλλά-σσω", "io cambio", "io scambio");
AllElements.addElement("ἀλλαγ-ή, -ῆς, ἡ", "cambio", "scambio", "cambiamento");
AllElements.addElement("ἀλλαχ-οῦ", "altrove");
AllElements.addElement("ἄλλος, -η, -ο", "altro");
AllElements.addElement("ἁμαρτ", "sbaglio", "errore", "errare", "sbagliare", "colpa");
AllElements.addElement("ἁμαρτ-άνω", "io sbaglio");
AllElements.addElement("ἁμαρτ-ία, -ας, ἡ", "sbaglio", "errore");
AllElements.addElement("ἁμάρτ-ημα, -τος, τό", "sbaglio", "errore", "reato");
AllElements.addElement("ν-ημερτ-ής, -ες", "infallibile");
AllElements.addElement("ἀναγκ", "necessità", "costrizione", "costringere");
AllElements.addElement("ἀναγκ-άζω", "io costringo");
AllElements.addElement("ἀνάγκ-η, -ης, -ἡ", "costrizione", "necessità", "destino", "ineluttabilità");
AllElements.addElement("ἀναγκ-αῖος, -α, -ον", "necessario", "inevitabile", "ineluttabile");
AllElements.addElement("ἀνδρ", "uomo", "maschio");
AllElements.addElement("ἀνήρ, ἀνδρ-ός, ὁ", "uomo", "maschio", "marito");
AllElements.addElement("ἀνδρ-εία, -ας, ἡ", "coraggio", "valore", "virilità");
AllElements.addElement("ἀνδρ-εῖος, -α, -ον", "coraggioso", "valoroso", "prode", "ardito");
AllElements.addElement("ἀνδρ-άποδον, -ου, τό", "schiavo", "servo", "prigioniero di guerra");
AllElements.addElement("ἀνδρ-αποδίζω", "io schiavizzo", "io rendo schiavo", "io vendo come schiavo");
AllElements.addElement("ἀνθρωπ", "uomo", "essere umano", "persona");
AllElements.addElement("ἄνθρωπ-ος, -ου, ὁ", "uomo", "essere umano", "persona");
AllElements.addElement("ἀνθρωπ-ικός, -ή, -όν", "umano", "antropico");
AllElements.addElement("ἀνθρώπ-ινος, -ον", "umano");
AllElements.addElement("ἀνθρώπ-ειος, -α, -ον", "umano");
AllElements.addElement("μισ-ανθρωπία, -ας, ἡ", "misantropia");
AllElements.addElement("μισ-άνθρωπος, -ον", "misantropo");
AllElements.addElement("φιλ-ανθρωπία, -ας, ἡ", "filantropia");
AllElements.addElement("φιλ-άνθρωπος, -ον", "filantropo");
AllElements.addElement("ἀριθμ", "numero", "conto");
AllElements.addElement("ἀριθμ-ός, -οῦ, ὁ", "numero", "totale", "somma", "quantità");
AllElements.addElement("ἀριθμ-έω", "io conto", "io enumero", "io annovero");
AllElements.addElement("ἄγ", "condurre", "guidare", "trascorrere");
AllElements.addElement("ἄγω", "io conduco", "io guido");
AllElements.addElement("ἀγ-ών, -ῶνος, ὁ", "agone", "gara", "lotta");
AllElements.addElement("ἀν-άγ-ω", "io salpo", "io parto");
AllElements.addElement("ἄξ-ιος, -α, -ον", "degno", "valido");
AllElements.addElement("ἀξ-ιόω", "io stimo degno", "io decido");
AllElements.addElement("ἀξ-ίωμα, -ατος, τό", "dignità", "stima", "onore", "reputazione", "valore");
AllElements.addElement("ἀξ-ία, -ας, ἡ", "pregio", "valore", "prezzo");
AllElements.addElement("ἀν-άξ-ιος, -ον", "indegno", "immeritevole", "immeritato");
AllElements.addElement("δι-άγω", "io trascorro", "io vivo", "io passo il tempo");
AllElements.addElement("στρατ-ηγ-ός, -οῦ, ὁ", "stratego", "comandante", "generale");
AllElements.addElement("ἀγγελ", "annunciare", "riferire");
AllElements.addElement("ἀγγέλλ-ω", "io riferisco", "io annuncio");
AllElements.addElement("ἀγγελ-ία, -ας, ἡ", "messaggio", "notizia", "annuncio");
AllElements.addElement("ἄγγελ-ος, -ου, ὁ", "messaggero", "nunzio");
AllElements.addElement("ἀπ-αγγέλλ-ω", "io riferisco", "io annuncio");
AllElements.addElement("εἰσ-αγγελ-ία, -ας, ἡ", "processo", "denuncia");
AllElements.addElement("εὐ-αγγέλ-ιον, -ου, τό", "buona novella");
AllElements.addElement("ἀγερ/ἀγορ/ἀγυρ", "radunare");
AllElements.addElement("ἀγείρ-ω", "io raduno", "io raccolgo", "io aduno");
AllElements.addElement("ἀγορ-ά, -ᾶς, ἡ", "piazza", "assemblea");
AllElements.addElement("ἀγορά-ομαι", "io mi raduno", "io parlo in pubblico");
AllElements.addElement("ἀγορ-εύω", "io parlo in pubblico");
AllElements.addElement("κατ-ηγορ-έω", "io accuso", "io parlo contro");
AllElements.addElement("κατ-ήγορ-ος, -ου, ὁ", "accusatore");
AllElements.addElement("πανήγυρις, -εως, ἡ", "assemblea");
AllElements.addElement("ἀγρ", "campo", "campagna", "terreno");
AllElements.addElement("ἀγρ-ός, -οῦ, ὁ", "campo", "campagna", "terreno");
AllElements.addElement("ἄγρ-ιος, -α, -ον", "agreste", "selvatico", "selvaggio");
AllElements.addElement("ἄγρ-οικος, -ον", "agreste", "rustico", "campagnolo", "rozzo");
AllElements.addElement("ἄγρ-οικία, -ας, ἡ", "rozzezza", "rusticità");
AllElements.addElement("ἀειδ/ἀοιδ/ᾀδ/ᾠδ", "canto", "cantare");
AllElements.addElement("ἀείδ-ω", "io canto");
AllElements.addElement("ᾄδ-ω", "io canto");
AllElements.addElement("ἀοιδ-ός, -οῦ, ὁ", "aedo", "cantore");
AllElements.addElement("ἀοιδ-ή, -ῆς, ἡ", "canto", "canzone", "poesia");
AllElements.addElement("ᾠδ-ή, -ῆς, ἡ", "canto", "poesia");
AllElements.addElement("ᾠδ-εῖον, -ου, τό", "odeon");
AllElements.addElement("αἰδ/αἰδε", "rispetto", "pudore");
AllElements.addElement("αἰδέομαι", "io rispetto", "io mi vergogno", "io provo vergogna", "io temo");
AllElements.addElement("αἰδ-ώς, -οῦς, ἡ", "rispetto", "pudore", "vergogna");
AllElements.addElement("αἰδ-οῖος, -α, -ον", "rispettoso", "degno di rispetto", "vergognoso", "rispettato");
AllElements.addElement("αἰν/αἰνε", "lodare", "lode", "elogio", "elogiare");
AllElements.addElement("αἰνέ-ω", "io lodo", "io elogio");
AllElements.addElement("ἔπ-αιν-ος, -ου, ὁ", "lode", "elogio");
AllElements.addElement("παρ-αινέ-ω", "io esorto", "io ammonisco");
AllElements.addElement("αἱρε", "prendere", "scegliere");
AllElements.addElement("αἱρέ-ω", "io prendo", "io scelgo");
AllElements.addElement("αἵρε-σις, -εως, ἡ", "scelta", "dottrina");
AllElements.addElement("ἀν-αιρέ-ω", "io elimino", "io uccido");
AllElements.addElement("δι-αίρε-σις, -εως, ἡ", "separazione");
AllElements.addElement("αἰσθ/αἰσθη", "sensazione", "percezione", "sentire", "accorgersi");
AllElements.addElement("αἰσθ-άν-ομαι", "io mi accorgo", "io percepisco", "io sento");
AllElements.addElement("αἴσθη-σις, -εως, ἡ", "sensazione", "percezione");
AllElements.addElement("αἰσθη-τός, -ή, -όν", "sensibile", "percepibile");
AllElements.addElement("αἰσθη-τικός, -ή, -όν", "sensibile", "sensoriale");
AllElements.addElement("αἰσχ", "brutto", "turpe");
AllElements.addElement("αἰσχ-ύνω", "io disonoro");
AllElements.addElement("αἰσχ-ύνομαι", "io mi vergogno");
AllElements.addElement("αἰσχ-ρός, -ά, -όν", "brutto", "turpe");
AllElements.addElement("αἰσχ-ύνη, -ης, ἡ", "vergogna");
AllElements.addElement("αἰτ/αἰτε", "chiedere", "domandare", "domanda", "richiesta");
AllElements.addElement("αἰτέ-ω", "io chiedo", "io domando", "io richiedo");
AllElements.addElement("αἴτη-σις, -εως, ἡ", "richiesta", "domanda");
AllElements.addElement("αἰτ-ία, -ας, ἡ", "causa", "colpa", "responsabilità");
AllElements.addElement("αἴτ-ιος, -α, -ον", "responsabile", "colpevole");
AllElements.addElement("ἀκου/ἀκοϜ/ἀκο", "ascoltare", "ascolto", "udito", "udire", "sentire");
AllElements.addElement("ἀκού-ω", "io ascolto", "io odo", "io sento");
AllElements.addElement("ἄκου-σμα, -τος, τό", "racconto", "ascolto");
AllElements.addElement("ὑπ-ήκοος, ὁ", "suddito", "sottomesso");

**/

AllElements.addElement("ναυ/ναϜ","nave","imbarcazione");
AllElements.addElement("ναῦς, νεώς, ἡ","nave","imbarcazione","battello");
AllElements.addElement("ναυ-τικός, -ή, -όν","nautico","navale");
AllElements.addElement("ναύ-αρχος, -ου, ὁ","navarco","comandante della nave","ammiraglio");
AllElements.addElement("ναυ-αρχέω","comando la nave","sono navarco");
AllElements.addElement("ναυ-μαχία, -ας, ἡ","battaglia navale");
AllElements.addElement("ναυ-αγία, -ας, ἡ","naufragio");
AllElements.addElement("νεμ-ε/νομ/νωμ","distribuire","pascolare");
AllElements.addElement("νέμ-ω","io distribuisco","io spartisco","io assegno");
AllElements.addElement("νέμ-ομαι","io abito");
AllElements.addElement("νόμ-ος, -ου, ὁ","legge","regola","consuetudine");
AllElements.addElement("νομο-θετ-έω","io legifero","io emano leggi");
AllElements.addElement("νομο-θέτ-ης, -ου, ὁ","legislatore");
AllElements.addElement("νομ-ή, -ῆς, ἡ","divisione","pascolo");
AllElements.addElement("νομ-άς, -άδος, ὁ","nomade","errante");
AllElements.addElement("νομ-ός, -οῦ, ὁ","pascolo");
AllElements.addElement("νομ-ίζω","io ritengo","io considero");
AllElements.addElement("νόμ-ισμα, -τος, τό","moneta");
AllElements.addElement("νέμ-εσις, -εως, ἡ","vendetta","indignazione");
AllElements.addElement("νησ","isola");
AllElements.addElement("νῆσ-ος, -ου, ἡ","isola");
AllElements.addElement("νησ-ιώτης, -ου, ὁ","isolano","abitante di un'isola");
AllElements.addElement("νικ","vittoria","vincere");
AllElements.addElement("νίκ-η, -ης, ἡ","vittoria","supremazia","successo");
AllElements.addElement("νικ-άω","io vinco","io prevalgo","io supero");
AllElements.addElement("νο","mente","pensiero","pensare");
AllElements.addElement("νοῦς, νοῦ, ὁ","mente","pensiero","ragionamento","intelligenza");
AllElements.addElement("νο-έω","io penso","io rifletto","io considero","io ragiono","io medito");
AllElements.addElement("νό-ησις, -εως, ἡ","pensiero","intelligenza","intelletto");
AllElements.addElement("νου-θετέω","io ammonisco","io consiglio","io rimprovero");
AllElements.addElement("εὔ-νο-ια, -ας, ἡ","benevolenza","affetto","disponibilità");
AllElements.addElement("εὔ-νους, -ουν","benevolo","affettuoso","disponibile");
AllElements.addElement("ὁμό-νο-ια, -ας, ἡ","concordia","unanimità");
AllElements.addElement("πρό-νο-ια, -ας, ἡ","prudenza","previdenza");
AllElements.addElement("νοσϝ","malattia","morbo");
AllElements.addElement("νόσ-ος, -ου, ἡ","malattia","morbo","contagio");
AllElements.addElement("νοσ-έω","io sono malato","io sono ammalato");
AllElements.addElement("νόσ-ημα, -τος, τό","malattia","morbo","contagio","male");
AllElements.addElement("νοσ-ερός, -ά, -όν","malato","contagioso","morboso");
AllElements.addElement("λαβ/ληβ","prendere","ricevere");
AllElements.addElement("λαμβ-άνω","io prendo");
AllElements.addElement("λαβ-ή, ῆς, ἡ","presa","impugnatura");
AllElements.addElement("λῆμ-μα, -τος, τό","guadagno","profitto","ricavo");
AllElements.addElement("λῆψ-ις, -εως, ἡ","guadagno","profitto","ricavo");
AllElements.addElement("λαθ/ληθ","essere nascosto","dimenticare","dimenticarsi","dimenticanza","oblio");
AllElements.addElement("λανθ-άνω","io sfuggo","io la faccio franca");
AllElements.addElement("λήθ-η, ἡ","dimenticanza","oblio");
AllElements.addElement("λάθ-ρᾳ","di nascosto","segretamente");
AllElements.addElement("ἀ-λήθ-εια, -ας, ἡ","verità");
AllElements.addElement("ἀ-ληθ-ής, -ές","vero");
AllElements.addElement("λαμπ","splendore","splendere","risplendere");
AllElements.addElement("λάμπ-ω","io splendo","io risplendo","io brillo");
AllElements.addElement("λαμπ-ρός, -ά, -όν","splendido","splendente","luminoso","raggiante");
AllElements.addElement("λαμπ-ρότης, -ητος, ἡ","splendore","luminosità","chiarezza");
AllElements.addElement("λαμπ-άς, -άδος, ἡ","fiaccola","torcia");
AllElements.addElement("λαχ/ληχ/λοχ","sorte");
AllElements.addElement("λαγχ-άνω","io ottengo in sorte");
AllElements.addElement("λάχ-ος, -ους, τό","sorteggio","sorte");
AllElements.addElement("λεγ/λογ","raccogliere","raccontare","dire","discorso","parola","parlare");
AllElements.addElement("λέγ-ω","io dico","io parlo","io affermo");
AllElements.addElement("λόγ-ος, -ου, ὁ","discorso","parola","ragione");
AllElements.addElement("ἀπο-λογ-έομαι","io mi difendo","io parlo in difesa");
AllElements.addElement("ἀπο-λογ-ία, -ας, ἡ","apologia","difesa","discorso di difesa");
AllElements.addElement("κατά-λογ-ος, -ου, ὁ","catalogo","lista","elenco","registro");
AllElements.addElement("λέξ-ις, -εως, ἡ","stile","discorso","dizione");
AllElements.addElement("δια-λέγ-ομαι","io converso","io dialogo");
AllElements.addElement("διά-λογ-ος, -ου, ὁ","dialogo","conversazione");
AllElements.addElement("λογ-ίζομαι","io calcolo","io conto","io ragiono");
AllElements.addElement("ἄ-λογ-ος, -ον","irrazionale","assurdo");
AllElements.addElement("λειπ/λοιπ/λιπ","lasciare","abbandonare","mancare");
AllElements.addElement("λείπ-ω","io lascio","io abbandono");
AllElements.addElement("λοιπ-ός, -ή, -όν","restante","rimanente");
AllElements.addElement("ἐκ-λείπ-ω","io cesso","io vengo meno","io smetto");
AllElements.addElement("ἔκ-λειψ-ις, -εως, ἡ","eclissi","eclisse");
AllElements.addElement("λιθ","pietra","sasso");
AllElements.addElement("λίθ-ος, -ου, ὁ","pietra","sasso");
AllElements.addElement("λίθ-ιν-ος, -η, -ον","di pietra","di sasso","di marmo");
AllElements.addElement("λιθ-οτομ-ία, -ας, ἡ","cava di pietra");
AllElements.addElement("λιθ-ώδης, -ες","sassoso","pietroso");
AllElements.addElement("λυ","sciogliere","distruggere");
AllElements.addElement("λύ-ω","io sciolgo","io distruggo");
AllElements.addElement("λύ-τρον, -ου, τό","riscatto");
AllElements.addElement("λύ-σις, -εως, ἡ","scioglimento","dissoluzione");
AllElements.addElement("λυσι-τελ-έω","io giovo");
AllElements.addElement("ἀνά-λυ-σις, -εως, ἡ","soluzione","dissoluzione","scioglimento");
AllElements.addElement("κατά-λυ-σις, -εως, ἡ","abbattimento","distruzione");
AllElements.addElement("κατα-λύ-ω","io abbatto","io distruggo");
AllElements.addElement("μαθ-η","imparare","apprendere","apprendimento");
AllElements.addElement("μανθ-άνω","io apprendo","io imparo");
AllElements.addElement("μάθ-ος, -ους, τό","apprendimento","conoscenza");
AllElements.addElement("μάθ-ησις, -εως, ἡ","apprendimento","conoscenza","istruzione");
AllElements.addElement("μαθη-τής, -οῦ, ὁ","scolaro","alunno","allievo","discepolo");
AllElements.addElement("ἀ-μαθ-ής, -ές","ignorante","ignaro","sciocco","stupido");
AllElements.addElement("ἀ-μαθ-ία, -ας, ἡ","ignoranza","stupidità");
AllElements.addElement("μαν/μην","impazzire","follia","pazzia","furia");
AllElements.addElement("μαίν-ω","io impazzisco","io infurio");
AllElements.addElement("μαν-ία, ας, ἡ","follia","pazzia");
AllElements.addElement("μαιν-άς, -άδος, ἡ","menade","baccante");
AllElements.addElement("μαντ","indovino","profeta","indovinare","profetizzare");
AllElements.addElement("μαντ-εύομαι","io profeto","io profetizzo","io do oracoli","io do un oracolo","io faccio profezie","io faccio una profezia");
AllElements.addElement("μάντ-ις, -εως, ὁ","profeta","indovino");
AllElements.addElement("μαντ-εία, -ας, ἡ","profezia","predizione","oracolo","divinazione");
AllElements.addElement("μαρτυρ","testimone","testimonianza","testimoniare","testimonio");
AllElements.addElement("μάρτυς, μάρτυρος, ὁ","testimone","testimonio","teste");
AllElements.addElement("μαρτυρ-έω","io testimonio","io attesto","io rendo testimonianza");
AllElements.addElement("μαρτύρ-ομαι","io testimonio","io attesto","io rendo testimonianza");
AllElements.addElement("μαρτυρ-ία, -ας, ἡ","testimonianza","attestazione","martirio");
AllElements.addElement("μαχ-η","combattere","combattimento","battaglia");
AllElements.addElement("μάχ-ομαι","io combatto","io lotto");
AllElements.addElement("μάχ-η, -ης, ἡ","battaglia","combattimento","lotta","scontro");
AllElements.addElement("ναυ-μαχ-ία, -ας, ἡ","battaglia navale","naumachia");
AllElements.addElement("σύμ-μαχ-ος, -ου, ὁ","alleato");
AllElements.addElement("συμ-μαχ-ία, -ας, ἡ","alleanza","lega","alleanza militare");
AllElements.addElement("μειγ/μιγ","mescolare","miscuglio");
AllElements.addElement("μείγ-νυμι","io mescolo");
AllElements.addElement("μίγ-νυμι","io mescolo");
AllElements.addElement("μίξ-ις, -εως, ἡ","mescolanza","miscuglio","commistione");
AllElements.addElement("μικ-τός, -ή, -όν","misto","mescolato");
AllElements.addElement("μελ-ε/μηλ","interesse","cura");
AllElements.addElement("μέλ-ει","interessa","importa");
AllElements.addElement("μελέ-τη, -ης, ἡ","cura","esercizio","allenamento","esercitazione","dissertazione");
AllElements.addElement("ἐπι-μέλ-εια, -ας, ἡ","cura","preoccupazione");
AllElements.addElement("ἀ-μέλ-εια, -ας, ἡ","trascuratezza","negligenza","incuria");
AllElements.addElement("μελλ-η","essere sul punto di","stare per");
AllElements.addElement("μέλλ-ω","io sono sul punto di","io sto per","io esito","io attendo","io aspetto");
AllElements.addElement("μέλλ-ον, -ντος, τό","futuro");
AllElements.addElement("μεν-η/μον/μν","aspettare","attendere","attesa","restare","rimanere");
AllElements.addElement("μέν-ω","io aspetto","io attendo","io rimango","io resto");
AllElements.addElement("μί-μν-ω","io aspetto","io rimango","io attendo","io resto");
AllElements.addElement("ἀνα-μέν-ω","io aspetto","io attendo");
AllElements.addElement("μόν-ιμος, -ον","durevole","perseverante");
AllElements.addElement("μερ/μορ/μαρ","parte");
AllElements.addElement("μείρ-ομαι","io spartisco","io divido");
AllElements.addElement("μέρ-ος, -ους, τό","parte","sezione");
AllElements.addElement("μοῖρ-α, -ας, ἡ","destino","sorte");
AllElements.addElement("εἰ-μαρ-μένη, -ης, ἡ","sorte","destino","destino assegnato");
AllElements.addElement("μόρ-ος, -ου, ὁ","sorte","destino","morte");
AllElements.addElement("μηχαν","macchina","strumento","mezzo","espediente","trucco");
AllElements.addElement("μηχαν-ή, ῆς, ἡ","macchina","strumento","mezzo","espediente","trucco","rimedio");
AllElements.addElement("μηχαν-άω","io tramo","io medito","io macchino","io escogito");
AllElements.addElement("ἀ-μήχαν-ος, -ον","impossibile","irrimediabile","privo di espedienti","incapace");
AllElements.addElement("πολυ-μήχαν-ος, -ον","versatile","ricco di espedienti");
AllElements.addElement("μιμ","imitare","imitazione","fingere","finzione");
AllElements.addElement("μιμ-έομαι","io imito","io fingo");
AllElements.addElement("μίμ-ησις, -εως, ἡ","imitazione","finzione");
AllElements.addElement("μνη/μνα","memoria","ricordo","ricordare");
AllElements.addElement("μι-μνή-σκω","io ricordo","io rammento");
AllElements.addElement("μνη-μοσύνη, -ης, ἡ","memoria","ricordo");
AllElements.addElement("μνή-μη, -ης, ἡ","ricordo","memoria");
AllElements.addElement("μνῆ-μα, -τος, τό","ricordo","monumento","tomba");
AllElements.addElement("μυθ","parola","racconto","mito");
AllElements.addElement("μῦθ-ος, -ου, ὁ","parola","racconto","mito");
AllElements.addElement("μυθ-έομαι","io parlo","io racconto");
AllElements.addElement("μυθο-λογέω","io racconto","io narro");
AllElements.addElement("κηρυκ","annunciare","bandire","proclamare");
AllElements.addElement("κηρύσσ-ω","io annuncio","io bandisco","io proclamo");
AllElements.addElement("κῆρυξ, -υκος, ὁ","araldo","banditore","messo","messaggero");
AllElements.addElement("κήρυγ-μα, -τος, τό","bando","proclama","annuncio","editto");
AllElements.addElement("κινδυν","pericolo","rischio","rischiare");
AllElements.addElement("κίνδυν-ος, -ου, ὁ","pericolo","rischio");
AllElements.addElement("κινδυν-εύω","io rischio","io corro il pericolo","io corro un pericolo","io corro pericolo");
AllElements.addElement("κλε/κλυ","fama","gloria");
AllElements.addElement("κλύ-ω","io ho fama");
AllElements.addElement("κλέ-ος, -ους, τό","fama","gloria","notorietà");
AllElements.addElement("ἀ-κλε-ής, -ές","inglorioso","disonorato","senza gloria");
AllElements.addElement("εὐ-κλε-ής, -ές","famoso","glorioso","celebre","rinomato");
AllElements.addElement("κλεπ/κλοπ/κλαπ","rubare","furto");
AllElements.addElement("κλέπ-τω","io rubo","io sottraggo");
AllElements.addElement("κλέπ-της, -ου, ὁ","ladro");
AllElements.addElement("κλῆμ-μα, -τος, τό","furto","imbroglio");
AllElements.addElement("κλοπ-ή, -ῆς, ἡ","furto","imbroglio");
AllElements.addElement("κοιν","comune","pubblico");
AllElements.addElement("κοιν-ός, -ή, -όν","comune","pubblico","collettivo");
AllElements.addElement("κοιν-ωνέω","io partecipo","io faccio parte","io mi accomuno");
AllElements.addElement("κοιν-ωνία, -ας, ἡ","comunanza","partecipazione","unione","associazione","comunità","società");
AllElements.addElement("κομ/κομιδ","curare","portare","accompagnare");
AllElements.addElement("κομίζ-ω","io trasporto","io porto","io accompagno");
AllElements.addElement("κομιδ-ή, -ῆς, ἡ","trasporto","accompagnamento");
AllElements.addElement("κομ-έω","io curo","io mantengo");
AllElements.addElement("κοπ","battere","percuotere","tagliare");
AllElements.addElement("κόπ-τω","io batto","io taglio");
AllElements.addElement("κοπ-ή, -ῆς, ἡ","taglio","percossa","colpo","botta");
AllElements.addElement("κόμ-μα, -τος, τό","pezzo");
AllElements.addElement("κοσμ","ordine","ornamento","cosmo","universo","ornare");
AllElements.addElement("κόσμ-ος, -ου, ὁ","ordine","cosmo","ornamento","universo");
AllElements.addElement("κόσμιος, -α, -ον","ordinato","moderato","saggio","onesto");
AllElements.addElement("κοσμ-έω","io ordino","io dispongo","io orno","io adorno","io abbellisco");
AllElements.addElement("ἄ-κοσμ-ος, -ον","disordinato","confuso","disadorno","sconveniente");
AllElements.addElement("ἀ-κοσμ-ία, -ας, ἡ","disordine","confusione","sregolatezza","semplicità");
AllElements.addElement("κρατ/καρτ","forza","potere","superiorità","supremazia");
AllElements.addElement("κράτ-ος, -ους, τό","forza","potere","supremazia");
AllElements.addElement("κρατ-έω","io vinco","io sono superiore","io mi impossesso","io domino","io regno","io sono forte");
AllElements.addElement("κρατ-ερός, -ά, -όν","forte","robusto","vigoroso");
AllElements.addElement("ἀριστο-κρατία, -ας, ἡ","aristocrazia","governo dei migliori");
AllElements.addElement("δημο-κρατία, -ας, ἡ","democrazia");
AllElements.addElement("κρι","giudicare");
AllElements.addElement("κρί-νω","io giudico","io distinguo","io separo");
AllElements.addElement("κρί-σις, -εως, ἡ","giudizio","scelta","separazione","processo","distinzione");
AllElements.addElement("κρι-τής, -οῦ, ὁ","giudice","arbitro","interprete");
AllElements.addElement("κρι-τήριον, -ου, τό","criterio","giudizio");
AllElements.addElement("δια-κρίν-ω","io distinguo","io separo","io divido");
AllElements.addElement("συγ-κρίν-ω","io accosto","io confronto","io paragono");
AllElements.addElement("σύγ-κρι-σις, -εως, ἡ","confronto","paragone","accostamento");
AllElements.addElement("ἄ-κρι-τος, -ον","ingiudicato","confuso","indistinto");
AllElements.addElement("ἀπο-κρί-νομαι","io rispondo");
AllElements.addElement("ὑπο-κρι-τής, -οῦ, ὁ","attore");
AllElements.addElement("κρυβ/κρυφ","nascondere","occultare");
AllElements.addElement("κρύπ-τω","io nascondo","io occulto","io celo");
AllElements.addElement("κρύφ-ιος, -α, -ον","nascosto","latente","segreto");
AllElements.addElement("κρυφ-αῖος, -α, -ον","nascosto","segreto","latente");
AllElements.addElement("κρυφ-ῇ","di nascosto","segretamente");
AllElements.addElement("κρύφ-α","di nascosto","segretamente");
AllElements.addElement("κρύβ-δην","di nascosto","segretamente");
AllElements.addElement("κτεν/κτον/κτα/κτιν","uccidere");
AllElements.addElement("κτείν-ω","io uccido","io ammazzo");
AllElements.addElement("ἀπο-κτιν-νύω","io uccido","io ammazzo");
AllElements.addElement("πατρο-κτόν-ος, -ον","patricida");
AllElements.addElement("κτη","acquisire","acquistare","possedere");
AllElements.addElement("κτά-ομαι","io acquisto","io conquisto","io mi procuro");
AllElements.addElement("κτῆ-σις, -εως, ἡ","possesso","acquisizione","conquista");
AllElements.addElement("κτῆ-μα, -τος, τό","possesso","conquista","acquisizione");
AllElements.addElement("θαν-α/θν-η","morte","morire");
AllElements.addElement("θάν-ατος, -ου, ὁ","morte");
AllElements.addElement("ἀπο-θνή-σκω","io muoio");
AllElements.addElement("θνη-τός, -ή, -όν","mortale");
AllElements.addElement("ἀ-θάν-ατος, -ον","immortale");
AllElements.addElement("ἀ-θανασία, -ας, ἡ","immortalità");
AllElements.addElement("θαυμ","meraviglia","ammirazione","ammirare","meravigliarsi");
AllElements.addElement("θαῦμα, -τος, τό","meraviglia","ammirazione","miracolo","fatto straordinario","stupore");
AllElements.addElement("θαυμ-άζω","io mi meraviglio","io ammiro","io mi stupisco","io onoro","io venero");
AllElements.addElement("θαυμ-αστός, -ή, -όν","ammirato","meraviglioso","straordinario","eccezionale","incredibile");
AllElements.addElement("θαυμ-άσιος, -α, -ον","meraviglioso","straordinario","incredibile");
AllElements.addElement("θε","dio","divinità","dea");
AllElements.addElement("θε-ός, -οῦ, ὁ","dio","divinità");
AllElements.addElement("θε-ός, -οῦ, ἡ","dea");
AllElements.addElement("θε-ά, -ᾶς, ἡ","dea");
AllElements.addElement("θεῖ-ος, -α, -ον","divino","sacro");
AllElements.addElement("θεα/θεη","spettacolo","guardare");
AllElements.addElement("θεά-ομαι","io ammiro","io assisto ad uno spettacolo","io vedo","io guardo");
AllElements.addElement("θέα-τρον, -ου, τό","teatro");
AllElements.addElement("θη/θε","collocare","porre","stabilire");
AllElements.addElement("τί-θη-μι","io pongo","io colloco");
AllElements.addElement("θέ-σις, -εως, ἡ","posizione","affermazione");
AllElements.addElement("θῆ-μα, -τος, τό","cassa","feretro");
AllElements.addElement("θέ-μα, -τος, τό","deposito","tema","tesoro");
AllElements.addElement("θηρ","fiera","caccia","cacciare");
AllElements.addElement("θήρ, θηρ-ός, ὁ","fiera","belva","animale");
AllElements.addElement("θήρ-α, -ας, ἡ","caccia","ricerca","brama","bottino");
AllElements.addElement("θηρ-ίον, -ου, τό","bestia","animale","belva","fiera");
AllElements.addElement("θηρ-άω","io caccio","io catturo","io cerco","io bramo");
AllElements.addElement("θηρ-εύω","io caccio","io vado a caccia","io catturo","io bramo","io ricerco");
AllElements.addElement("θηρ-ευτής, -οῦ, ὁ","cacciatore");
AllElements.addElement("θυμ","animo","coraggio","mente");
AllElements.addElement("θυμ-ός, -οῦ, ὁ","animo","coraggio","animosità");
AllElements.addElement("ἐπι-θυμ-ία, -ας, ἡ","desiderio","passione","voglia","bramosia");
AllElements.addElement("ἐπι-θυμ-έω","io desidero","io bramo");
AllElements.addElement("ἀ-θυμ-ία, -ας, ἡ","scoraggiamento","avvilimento");
AllElements.addElement("ἄ-θυμ-ος, -ον","scoraggiato","avvilito","abbattuto");
AllElements.addElement("θυρ","porta");
AllElements.addElement("θύρ-α, -ας, ἡ","porta","ingresso","soglia");
AllElements.addElement("θυρ-ίς, -ίδος, ἡ","porticina","finestra");
AllElements.addElement("ἀμφί-θυρ-ος, -ον","a due porte");
AllElements.addElement("θυρ-ωρ-ός, -οῦ, ὁ","portinaio","portiere","custode");
AllElements.addElement("θυ","sacrificio","sacrificare","fumo");
AllElements.addElement("θυ-σία, -ας, ἡ","sacrificio","rito","festa","cerimonia");
AllElements.addElement("θύ-ω","io sacrifico","io celebro","io festeggio","io immolo","io faccio sacrifici","io faccio un sacrificio");
AllElements.addElement("ἰα","curare","medicare","guarire");
AllElements.addElement("ἰά-ομαι","io curo","io guarisco");
AllElements.addElement("ἰα-τρός, -οῦ, ὁ","medico","curatore","guaritore");
AllElements.addElement("ἰα-τρικός, -ή, -όν","medico");
AllElements.addElement("ἰδ/οἰδ/εἰδ","vedere","sapere","aspetto","figura");
AllElements.addElement("εἶδ-ον","io vidi");
AllElements.addElement("οἶδ-α","io so","io conosco");
AllElements.addElement("ἰδ-έα, -ας, ἡ","apparenza","figura","forma");
AllElements.addElement("εἶδ-ος, -ους, τό","aspetto","forma","figura");
AllElements.addElement("εἴδ-ωλον, -ου, τό","immagine","simulacro","fantasma","fantasia","idea","immaginazione");
AllElements.addElement("ἱστ-ορέω","io indago","io esploro","io mi informo","io domando","io ricerco");
AllElements.addElement("ἱστ-ορία, -ας, ἡ","indagine","storia","ricerca");
AllElements.addElement("ἵσ-τωρ, -τορος, ὁ","conoscitore","esperto","giudice");
AllElements.addElement("ἱερ","sacro");
AllElements.addElement("ἱερ-ός, -ά, -όν","sacro","divino");
AllElements.addElement("ἱερ-όν, τό","sacerdote","ministro");
AllElements.addElement("ἱερ-εῖον, τό","vittima","ministro");
AllElements.addElement("ἱερ-εύς, -έως, ὁ","sacerdote","ministro");
AllElements.addElement("ἱέρ-εια, -ας, ἡ","sacerdotessa");
AllElements.addElement("ἱερ-εύω","io sacrifico","io compio un sacrificio");
AllElements.addElement("ἱερ-οσυλία, -ας, ἡ","sacrilegio","furto sacrilego");
AllElements.addElement("ἱκ/ἡκ","arrivare","giungere");
AllElements.addElement("ἀφ-ικ-νέομαι","io giungo","io arrivo","io vengo");
AllElements.addElement("ἥκ-ω","io arrivo","io giungo","io vengo");
AllElements.addElement("ἱκ-ανός, -ή, -όν","capace","adatto","opportuno");
AllElements.addElement("προσ-ήκει","conviene","si addice","è giusto");
AllElements.addElement("ἱππ","cavallo","cavalleria");
AllElements.addElement("ἵππ-ος, -ου, ὁ","cavallo");
AllElements.addElement("ἵππ-ος, -ου, ἡ","cavalla","cavalleria");
AllElements.addElement("ἱππ-εύω","io cavalco","io sono cavaliere","io vado a cavallo");
AllElements.addElement("ἱππ-εύς, -εως, ὁ","cavaliere");
AllElements.addElement("ἱππ-ικός, -ή, -όν","equino","ippico");
AllElements.addElement("καλ","bello","bellezza");
AllElements.addElement("καλ-ός, -ή, -όν","bello","elegante","nobile","buono","virtuoso");
AllElements.addElement("κάλ-λος, -ους, τό","bellezza","eleganza","bontà");
AllElements.addElement("καλ-λωπίζω","io abbellisco","io rendo bello");
AllElements.addElement("καλ-η/κλη","chiamare");
AllElements.addElement("καλέ-ω","io chiamo");
AllElements.addElement("κλῆ-σις, -εως, ἡ","chiamata","convocazione");
AllElements.addElement("ἔγ-κλη-μα, -τος, τό","accusa","denuncia");
AllElements.addElement("ἐκ-κλη-σία, -ας, ἡ","assemblea","riunione");
AllElements.addElement("ἀνα-καλέω","io richiamo");
AllElements.addElement("καυ","bruciare");
AllElements.addElement("καί-ω","io brucio","io accendo","io incendio");
AllElements.addElement("καῦ-μα, -τος, τό","calore","calura");
AllElements.addElement("ἀνα-καί-ω","io brucio","io accendo","io incendio");
AllElements.addElement("κει/κοι","giacere","stare");
AllElements.addElement("κεῖ-μαι","io giaccio","io sto","io mi trovo");
AllElements.addElement("κειμ-ήλιον, -ου, τό","tesoro","cimelio");
AllElements.addElement("κοί-τη, -ης, ἡ","letto","giaciglio");
AllElements.addElement("κοι-μάω","io addormento","io faccio dormire");
AllElements.addElement("ἄ-κοι-τις, -ιος, ἡ","moglie","sposa");
AllElements.addElement("κελευ","ordinare","comandare");
AllElements.addElement("κελεύ-ω","io ordino","io esorto","io invito");
AllElements.addElement("κέλευ-σις, -εως, ἡ","ordine","esortazione","comando");
AllElements.addElement("κέλευ-σμα, -τος, τό","ordine","esortazione","invito");
AllElements.addElement("κερδ","guadagno","lucro","profitto","vantaggio","guadagnare");
AllElements.addElement("κέρδ-ος, -ους, τό","guadagno","lucro","vantaggio");
AllElements.addElement("κερδ-αίνω","io guadagno","io approfitto","io traggo vantaggio");
AllElements.addElement("αἰσχρο-κερδ-ής, -ές","avido");
AllElements.addElement("κερδ-αλέος, -α, -ον","vantaggioso","utile","scaltro");
AllElements.addElement("κηρυκ","annunciare","bandire","proclamare");
AllElements.addElement("κηρύσσ-ω","io annuncio","io bandisco","io proclamo");
AllElements.addElement("κῆρυξ, -υκος, ὁ","araldo","banditore","messo","messaggero");
AllElements.addElement("κήρυγ-μα, -τος, τό","bando","proclama","annuncio","editto");
AllElements.addElement("κινδυν","pericolo","rischio","rischiare");
AllElements.addElement("κίνδυν-ος, -ου, ὁ","pericolo","rischio");
AllElements.addElement("κινδυν-εύω","io rischio","io corro il pericolo","io corro un pericolo","io corro pericolo");
AllElements.addElement("ζηλ","invidia","invidiare","emulazione");
AllElements.addElement("ζῆλ-ος, -ου, ὁ","invidia","emulazione","gelosia");
AllElements.addElement("ζηλ-όω","io invidio","io emulo");
AllElements.addElement("ζημ","pena","punizione","castigo","punire","castigare");
AllElements.addElement("ζημ-ία, -ας, ἡ","pena, punizione","castigo","danno","perdita","multa", "ammenda");
AllElements.addElement("ζημ-ιόω","io punisco","io castigo","io danneggio","io multo");
AllElements.addElement("ζω/ζη/ζο","vivere","vita","animale");
AllElements.addElement("ζά-ω","io vivo","io sono vivo");
AllElements.addElement("ζω-ή, -ῆς, ἡ","vita");
AllElements.addElement("ζω-ός, -ή, -όν","vivo","vivente");
AllElements.addElement("ζῶ-ον, -ου, τό","animale","vivente","essere vivente");
AllElements.addElement("ζω-γράφ-ος, -ου, ὁ","pittore");
AllElements.addElement("ἡ/ἑ","gettare","lanciare","mandare");
AllElements.addElement("ἵη-μι","io getto","io spingo","io mando","io lancio");
AllElements.addElement("ἀφ-ίη-μι","io allontano","io caccio","io mando via","io lascio andare");
AllElements.addElement("συν-ίη-μι","io comprendo","io capisco");
AllElements.addElement("σύν-εσις, -εως, ἡ","comprensione","intelligenza");
AllElements.addElement("συν-ετός, -ή, -όν","intelligente","assennato","esperto","comprensibile");
AllElements.addElement("ἡγε/ἡγη","comandare","guidare","comando","guida","opinione","ritenere");
AllElements.addElement("ἡγέ-ομαι","io guido","io ritengo");
AllElements.addElement("ἡγε-μών, -όνος, ὁ","guida","capo");
AllElements.addElement("ἡγε-μονία, -ας, ἡ","comando","superiorità","guida","egemonia");
AllElements.addElement("δι-ήγε-σις, -εως, ἡ","racconto","narrazione");
AllElements.addElement("ἡδ","dolce","piacere");
AllElements.addElement("ἥδ-ομαι","io mi rallegro","io godo","io gioisco");
AllElements.addElement("ἡδ-ύς, -εῖα, ύ","dolce","piacevole");
AllElements.addElement("ἡδ-ονή, -ῆς, ἡ","piacere","godimento","gioia");
AllElements.addElement("ἡσυχ","tranquillo","tranquillità");
AllElements.addElement("ἡσυχ-ία, -ας, ἡ","tranquillità","calma","quiete","pace","riposo");
AllElements.addElement("ἥσυχ-ος, -ον","tranquillo","calmo","quieto","placido","pacifico");
AllElements.addElement("ἡσυχ-άζω","io sono tranquillo","io sono calmo","io sono in pace");
AllElements.addElement("ἐδ/ὀδ/ὠδ","cibo","alimento","mangiare","cibarsi");
AllElements.addElement("ἐσ-θίω","mangio");
AllElements.addElement("ἐδ-ωδ-ή, -ῆς, ἡ","cibo","alimento");
AllElements.addElement("ὀδ-ούς, -όντος, ὁ","dente");
AllElements.addElement("ἐθ/ἠθ/ὠθ","abitudine");
AllElements.addElement("ἔθ-ος, ους, τό","abitudine","tradizione");
AllElements.addElement("ἦθ-ος, -ους, τό","abitudine","carattere","personalità","indole");
AllElements.addElement("εὐ-ήθης, -ες","buono","semplice","onesto","dabbene","ingenuo");
AllElements.addElement("εὐ-ήθει-α, -ας, ἡ","bontà","semplicità","dabbenaggine","ingenuità");
AllElements.addElement("ἐθ-ίζω","io abituo");
AllElements.addElement("εἰ/ἰ","andare");
AllElements.addElement("εἶ-μι","io vado","io andrò");
AllElements.addElement("ἄπ-ει-μι","io me ne vado","io parto","io vado via");
AllElements.addElement("ἔξ-ει-μι","io esco","io vado fuori");
AllElements.addElement("ἐλευθερ","libero","libertà");
AllElements.addElement("ἐλεύθερ-ος, -α, -ον","libero","indipendente","liberale");
AllElements.addElement("ἐλευθερ-ία, -ας, ἡ","libertà","liberalità","indipendenza");
AllElements.addElement("ἐλευθερ-όω","io libero","io rendo libero");
AllElements.addElement("ἐλπιδ/ἐλπ/ὀλπ","sperare","speranza","aspettativa","prevedere");
AllElements.addElement("ἐλπίζ-ω","io spero","io prevedo");
AllElements.addElement("ἐλπίς, -ίδος, ἡ","speranza","previsione");
AllElements.addElement("ἄ-ελπ-τος, -ον","insperato","imprevisto","inatteso");
AllElements.addElement("ἐπ/ὀπ","parola","dire");
AllElements.addElement("ἔπ-ος, -ους, τό","parola","verso");
AllElements.addElement("εἶπ-ον","io dissi");
AllElements.addElement("ἐρ/ῥη","parola","parlare","dire");
AllElements.addElement("εἴρ-ω","io dico","io parlo");
AllElements.addElement("ῥῆ-σις, -εως, ἡ","discorso","intervento");
AllElements.addElement("παρ-ρη-σία, -ας, ἡ","libertà di parola","confidenza","franchezza","licenza");
AllElements.addElement("ῥή-τωρ, -τορος, ὁ","oratore","retore","politico","uomo politico");
AllElements.addElement("ῥητορική (τέχνη), ἡ","retorica");
AllElements.addElement("ἐργ/ὀργ/ῥεγ","lavorare","lavoro","azione","opera");
AllElements.addElement("ἔργ-ον, -ου, τό","azione","opera","lavoro","impresa");
AllElements.addElement("ἐργ-άζομαι","io lavoro","io faccio");
AllElements.addElement("εὐ-εργ-έτης, -ου, ὁ","benefattore");
AllElements.addElement("γε-ωργ-ός, -οῦ, ὁ","agricoltore","contadino");
AllElements.addElement("ἐν-έργ-εια, -ας, ἡ","efficacia","attività");
AllElements.addElement("ὄργ-ανον, -ου, τό","strumento");
AllElements.addElement("ῥέζ-ω","io sacrifico","io celebro un rito","io offro un sacrificio");
AllElements.addElement("ἐριδ","lite","litigare","litigio","rivalità","gara");
AllElements.addElement("ἔρις, -ιδος, ἡ","lite","litigio","discordia","contesa");
AllElements.addElement("ἐρίζ-ω","io litigo","io contendo","io gareggio");
AllElements.addElement("εὑρ-ε/εὑρ-η","trovare","inventare","escogitare","invenzione");
AllElements.addElement("εὑρ-ίσκω","io trovo","io invento","io escogito");
AllElements.addElement("εὕρε-σις, -εως, ἡ","scoperta","invenzione","trovata");
AllElements.addElement("εὕρη-μα, -τος, τό","scoperta","invenzione","trovata");
AllElements.addElement("εὑρε-τής, -οῦ, ὁ","inventore","scopritore");
AllElements.addElement("ἐχ/ἑχ/σχ-ε/σχ-η/ὀχ","avere","tenere","stare");
AllElements.addElement("ἔχ-ω","io ho","io possiedo","io tengo");
AllElements.addElement("σχέ-σις, -εως, ἡ","condizione","disposizione","situazione");
AllElements.addElement("σχῆ-μα, -τος, τό","aspetto","figura","portamento");
AllElements.addElement("ἠνί-οχος, -ου, ὁ","auriga","cocchiere");
AllElements.addElement("δε/δη","legare");
AllElements.addElement("δέ-ω","io lego");
AllElements.addElement("δε-σμός, -οῦ, ὁ","legame","catena","ceppo","vincolo");
AllElements.addElement("δε-σμώτης, -ου, ὁ","prigioniero");
AllElements.addElement("δε-σμώτηριον, -ου, τό","prigione","carcere");
AllElements.addElement("δέ-σις, -εως, ἡ","legame","vincolo");
AllElements.addElement("δε-ι/δοι/δι","temere","timore","paura");
AllElements.addElement("δείδ-ω","io temo","io ho paura");
AllElements.addElement("δέ-ος, -ους, τό","timore","paura");
AllElements.addElement("δει-λός, -ή, -όν","vile","vigliacco");
AllElements.addElement("δει-νός, -ή, -όν","terribile","straordinario","eccezionale");
AllElements.addElement("δεικ","mostrare","indicare");
AllElements.addElement("δείκ-νυμι","io mostro","io indico","io dimostro");
AllElements.addElement("ἔv-δειξ-ις, -εως, ἡ","denuncia","delazione");
AllElements.addElement("ἐπί-δειξ-ις, -εως, ἡ","dimostrazione","indicazione");
AllElements.addElement("παρά-δειγ-μα, -τος, τό","modello","esempio");
AllElements.addElement("δεχ/δεκ/δοχ/δοκ","accettare","accogliere","ricevere");
AllElements.addElement("δέχ-ομαι","io accetto","io ricevo");
AllElements.addElement("δια-δέχ-ομαι","io eredito","io succedo");
AllElements.addElement("δια-δοχ-ή, -ῆς, ἡ","eredità","successione");
AllElements.addElement("δωρο-δοκ-έω","io mi lascio corrompere","io corrompo");
AllElements.addElement("δευ/(δεϜ)/δε-η","mancanza","mancare","bisogno");
AllElements.addElement("δέ-ω, δέ-ομαι","io chiedo","io ho bisogno");
AllElements.addElement("δεῖ","bisogna");
AllElements.addElement("ἐν-δε-ής, -ές","bisognoso","manchevole");
AllElements.addElement("δέ-ον, -τό","necessità","necessario","dovere");
AllElements.addElement("δηλ","chiaro","evidente","ovvio","palese");
AllElements.addElement("δῆλ-ος, -η, -ον","chiaro","ovvio","palese","evidente");
AllElements.addElement("δηλ-όω","io chiarisco","io manifesto","io mostro","io rivelo");
AllElements.addElement("ἄ-δηλ-ος, -ον","incerto","sconosciuto","oscuro","ignoto");
AllElements.addElement("δημ","popolo","demo");
AllElements.addElement("δῆμ-ος, -ου, ὁ","popolo","paese");
AllElements.addElement("δημ-όσιος, -α, -ον","pubblico","popolare","comune","statale");
AllElements.addElement("δημ-αγωγός, -οῦ, ὁ","demagogo","capopopolo");
AllElements.addElement("δημ-εύω","io confisco","io rendo pubblico");
AllElements.addElement("διδακ/διδαχ","insegnare","insegnamento");
AllElements.addElement("διδάσκ-ω","io insegno");
AllElements.addElement("διδάσκ-αλος, -ου, ὁ","maestro","insegnante");
AllElements.addElement("διδασκαλ-εῖον, -ου, τό","scuola");
AllElements.addElement("διδαχ-ή, -ῆς, ἡ","insegnamento");
AllElements.addElement("δίδαξις, -εως, ἡ","insegnamento");
AllElements.addElement("δικ","giustizia");
AllElements.addElement("δίκ-η, -ης, ἡ","giustizia","processo");
AllElements.addElement("δικ-άζω","io amministro la giustizia","io giudico");
AllElements.addElement("δικ-αστής, -οῦ, ὁ","giudice");
AllElements.addElement("δικ-αστήριον, -ου, τό","tribunale");
AllElements.addElement("δίκ-αιος, -α, -ον","giusto");
AllElements.addElement("δικ-αιοσύνη, -ης, ἡ","giustizia");
AllElements.addElement("ἄ-δικ-ος, -ον","ingiusto");
AllElements.addElement("ἀ-δίκ-ημα, -τος, τό","ingiustizia","azione ingiusta","reato");
AllElements.addElement("ἀ-δικ-ία, -ας, ἡ","ingiustizia");
AllElements.addElement("δοκ-η","sembrare","credere","opinione","fama");
AllElements.addElement("δοκέ-ω","io sembro","io ritengo");
AllElements.addElement("δοκεῖ","sembra");
AllElements.addElement("δόξ-α, -ης, ἡ","opinione","fama");
AllElements.addElement("δοξ-άζω","io ritengo","io credo");
AllElements.addElement("δόγ-μα, -τος, τό","opinione","credenza","reputazione");
AllElements.addElement("δόκ-ησις, -εως, ἡ","opinione","credenza","reputazione");
AllElements.addElement("προσ-δοκ-άω","io prevedo","io mi aspetto");
AllElements.addElement("ἀ-προσ-δόκ-ητος, -ον","inatteso","imprevisto");
AllElements.addElement("ἄ-δοξ-ος, -ον","inglorioso","sconosciuto","senza gloria");
AllElements.addElement("ἔν-δοξ-ος, -ον","famoso","celebre","rinomato");
AllElements.addElement("παρά-δοξ-ος, -ον","inatteso","imprevisto","inaspettato","imprevedibile");
AllElements.addElement("δουλ","schiavo","servo","schiavitù","servitù");
AllElements.addElement("δοῦλ-ος, -ου, ὁ","schiavo","servo");
AllElements.addElement("δουλ-εύω","io sono schiavo","io servo","io sono servo");
AllElements.addElement("δουλ-εία, -ας, ἡ","servitù","schiavitù");
AllElements.addElement("δυνα","potere","potenza");
AllElements.addElement("δύνα-μαι","io posso","io sono capace","io sono in grado");
AllElements.addElement("δύνα-μις, -εως, ἡ","potenza","capacità","forza","forza militare","esercito");
AllElements.addElement("δυνα-τός, -ή, όν","possibile","capace","potente");
AllElements.addElement("ἄ-δύνα-τος, όν","impossibile","incapace","invalido");
AllElements.addElement("δυνά-στης, -ου, ὁ","capo","re","dinasta");
AllElements.addElement("δυνα-στεύω","io domino","io ho il potere","io governo","io esercito il potere");
AllElements.addElement("δυνα-στεία, -ας, ἡ","potenza","potere");
AllElements.addElement("δω/δο","dare","donare","dono");
AllElements.addElement("δί-δω-μι","io do","io dono","io offro");
AllElements.addElement("δῶ-ρον, -ου, τό","dono","regalo","offerta");
AllElements.addElement("δω-ρεά, -ᾶς, ἡ","dono","regalo","offerta");
AllElements.addElement("δωρο-δοκ-έω","io accetto doni","io mi faccio corrompere","io corrompo");
AllElements.addElement("δωρο-δοκ-ία, -ας, ἡ","corruttibilità","venalità","corruzione");
AllElements.addElement("δό-σις, -εως, ἡ","contributo","donazione");
AllElements.addElement("δό-τήρ, -ος, ὁ","dispensatore","donatore");
AllElements.addElement("προ-δί-δω-μι","io tradisco");
AllElements.addElement("προ-δό-της, -ου, ὁ","traditore");
AllElements.addElement("προ-δο-σία, -ας, ἡ","tradimento");
AllElements.addElement("γαμ-ε","sposare","sposarsi","nozze","matrimonio");
AllElements.addElement("γαμέ-ω","io sposo");
AllElements.addElement("γάμ-ος, -ου, ὁ","matrimonio","nozze","sposalizio");
AllElements.addElement("γαμέ-της, -ου, ὁ","marito","sposo");
AllElements.addElement("γεν-ε/γον/γν","nascere","generare","generazione","nascita","genere","stirpe");
AllElements.addElement("γί-γν-ομαι","io nasco","io divento","io sono");
AllElements.addElement("γεν-νάω","io genero","io produco");
AllElements.addElement("γέν-ος, -ους, τό","genere","stirpe","razza","famiglia","specie");
AllElements.addElement("γένε-σις, -εως, ἡ","generazione","origine","nascita");
AllElements.addElement("γενεά, -ᾶς, ἡ","generazione","stirpe","razza","specie");
AllElements.addElement("γον-εύς, -έως, ὁ","genitore");
AllElements.addElement("γν-ήσιος, -α, ον","legittimo","autentico");
AllElements.addElement("γεν-ναῖος, -α, ον","nobile");
AllElements.addElement("πρό-γον-ος, -ον","antenato","avo","progenitore");
AllElements.addElement("εὐ-γεν-ής, -ές","nobile");
AllElements.addElement("γηρ","vecchio","vecchiaia");
AllElements.addElement("γῆρ-ας, -ως, τό","vecchiaia","vecchiezza");
AllElements.addElement("γηρ-άσκω","io invecchio","io divento vecchio","io sono vecchio");
AllElements.addElement("γηρ-αιός, -ά, -όν","vecchio","anziano");
AllElements.addElement("γνο/γνω","conoscere","conoscenza");
AllElements.addElement("γι-γνώ-σκω","io conosco","io so");
AllElements.addElement("γνῶ-σις, -εως, ἡ","conoscenza");
AllElements.addElement("πρό-γνω-σις, -εως, ἡ","previsione","prognosi");
AllElements.addElement("γνω-τός, -ή, -όν","conosciuto","noto","famoso","celebre");
AllElements.addElement("γνώ-μη, -ης, ἡ","conoscenza","opinione","intelligenza");
AllElements.addElement("συγ-γνώ-μη, -ης, ἡ","comprensione","perdòno");
AllElements.addElement("ἀνα-γι-γνώ-σκω","leggo","riconosco");
AllElements.addElement("ἀ-γνο-έω","io ignoro","io non so");
AllElements.addElement("ἄ-γνο-ια, -ας, ἡ","ignoranza");
AllElements.addElement("ἄ-γνο-τος, -ον","ignorato","sconosciuto","ignoto");
AllElements.addElement("γραφ","scrivere","scrittura","disegnare","disegno");
AllElements.addElement("γράφ-ω","io scrivo","io disegno");
AllElements.addElement("γραφ-ή, -ῆς, ἡ","scrittura","scritto","disegno");
AllElements.addElement("γραφ-εύς, -έως, ὁ","scrittore","disegnatore");
AllElements.addElement("γράμ-μα, -τος, τό","scrittura","disegno","lettera");
AllElements.addElement("γραμ-ματεύς, -έως, ὁ","scrivano","segretario");
AllElements.addElement("ἄγραφος, -ον","non scritto");
AllElements.addElement("γυμν","nudo","denudare");
AllElements.addElement("γυμν-ός, -ή, -όν","nudo","spoglio","svestito");
AllElements.addElement("γυμνό-ω","io spoglio","io denudo","io scopro","io svesto");
AllElements.addElement("γυμν-άσιον, -ου, τό","ginnasio","palestra");
AllElements.addElement("γυναικ","donna");
AllElements.addElement("γυνή, γυναικ-ός, ἡ","donna","moglie");
AllElements.addElement("γυναικ-εῖος, -α, -ον","femminile","muliebre","di donna","da donna");

    }
}

